Repository kookmin-sw/capstone-2025-08, pull requests merged in 2025-05, with the labels that each got.

#79 [ BE ] feat/#56 모델 서버 추론 완료 후 응용 서버 호출 기능 추가
  ai/config.py
  ai/core/image_processor.py
  ai/core/sqs.py
  ai/requirements.txt
Labels: ✨Feature, 😎BE

#83 [ BE ] feat/#82 프로젝트 생성 기능 추가
  backend/build.gradle
  backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
  backend/src/main/java/site/pathos/domain/project/dto/request/CreateProjectRequestDto.java
  backend/src/main/java/site/pathos/domain/project/entity/Project.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/domain/user/repository/UserRepository.java
  backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
  backend/src/main/java/site/pathos/global/aws/s3/dto/S3UploadFileDto.java
  backend/src/main/java/site/pathos/global/config/AsyncConfig.java
  backend/src/main/java/site/pathos/global/config/ImageUploadExecutorConfig.java
Labels: ✨Feature, 😎BE

#78 [ FE ] feat/#77 백엔드 타일링 테스트 페이지 구현
  frontend/package.json
  frontend/src/app/main/layout.tsx
  frontend/src/app/main/projects/[id]/page.tsx
  frontend/src/app/main/projects/page.tsx
  frontend/src/app/test/page.tsx
  frontend/src/components/annotation/annotation-header/index.tsx
  frontend/src/components/annotation/annotation-test-viewer/index.tsx
  frontend/src/components/common/page-title/index.tsx
  frontend/src/components/common/search-bar/index.tsx
  frontend/src/components/common/status-badge/index.tsx
  frontend/src/components/projects/project-card/index.tsx
  frontend/src/components/projects/project-info-card/index.tsx
  frontend/src/components/projects/subproject-card/index.tsx
  frontend/src/components/projects/subproject-table/index.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/data/dummy.ts
  frontend/src/types/project-schema.ts
  frontend/yarn.lock
Labels: ✅Test, 🌈FE

#91 [ FE ] feat/#87 로그인 및 회원가입 페이지 퍼블리싱
  .github/pull_request_template.md
  frontend/package.json
  frontend/public/images/login-splash.png
  frontend/src/app/auth/page.tsx
  frontend/src/components/auth/login-form/index.tsx
  frontend/src/components/auth/signup-form/index.tsx
  frontend/src/components/icons/pathos-symbol-logo/index.tsx
  frontend/src/components/icons/pathos-text-logo/index.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/styles/globals.css
  frontend/yarn.lock
Labels: ✨Feature, 🌈FE

#95 [ FE ] feat/#92 어노테이션 페이지 디벨롭
  frontend/package.json
  frontend/src/app/main/projects/[id]/page.tsx
  frontend/src/components/annotation/annotation-control-panel/index.tsx
  frontend/src/components/annotation/annotation-header/index.tsx
  frontend/src/components/annotation/annotation-tool/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/components/projects/project-card/index.tsx
  frontend/src/components/ui/slider.tsx
  frontend/src/data/dummy.ts
  frontend/src/stores/annotation-shared.ts
  frontend/src/types/project-schema.ts
  frontend/src/utils/canvas-image-utils.ts
  frontend/src/utils/canvas-roi-utils.ts
  frontend/src/utils/canvas-utils.ts
  frontend/yarn.lock
Labels: ✨Feature, 🌈FE

#99 [ BE ] feat/#97 프로젝트 수정 및 삭제 기능 추가
  backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
  backend/src/main/java/site/pathos/domain/project/dto/request/UpdateProjectRequestDto.java
  backend/src/main/java/site/pathos/domain/project/entity/Project.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
Labels: ✨Feature, 😎BE

#102 [ BE ] release: 백엔드 모델 서버 작업물 업로드
  ai/.dockerignore
  ai/.gitignore
  ai/Dockerfile
  ai/config.py
  ai/core/__init__.py
  ai/core/image_processor.py
  ai/core/sqs.py
  ai/main.py
  ai/requirements.txt
Labels: 🌏Deploy, 😎BE

#105 [BE] fix: 폴더명 backend-ai로 변경
  backend-ai/.dockerignore
  backend-ai/.gitignore
  backend-ai/Dockerfile
  backend-ai/app.py
  backend-ai/config.py
  backend-ai/core/__init__.py
  backend-ai/core/image_processor.py
  backend-ai/core/sqs.py
  backend-ai/main.py
  backend-ai/requirements.txt
Labels: 🔥HotFix

#109 [ FE ] feat/#108 Open API Generate 설정
  frontend/openapitools.json
  frontend/package.json
  frontend/scripts/generate-openapi.ts
  frontend/src/components/annotation/annotation-tool/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/generated-api/.openapi-generator-ignore
  frontend/src/generated-api/.openapi-generator/FILES
  frontend/src/generated-api/.openapi-generator/VERSION
  frontend/src/generated-api/apis/AnnotationHistoryControllerApi.ts
  frontend/src/generated-api/apis/ModelServerControllerApi.ts
  frontend/src/generated-api/apis/ProjectControllerApi.ts
  frontend/src/generated-api/apis/RoiControllerApi.ts
  frontend/src/generated-api/apis/SubProjectControllerApi.ts
  frontend/src/generated-api/apis/index.ts
  frontend/src/generated-api/index.ts
  frontend/src/generated-api/models/AnnotationHistoryResponseDto.ts
  frontend/src/generated-api/models/AnnotationHistorySummaryDto.ts
  frontend/src/generated-api/models/CellDetail.ts
  frontend/src/generated-api/models/CreateProjectRequestDto.ts
  frontend/src/generated-api/models/GetProjectsResponseDetailDto.ts
  frontend/src/generated-api/models/GetProjectsResponseDto.ts
  frontend/src/generated-api/models/GetProjectsResponseModelsDto.ts
  frontend/src/generated-api/models/LabelDto.ts
  frontend/src/generated-api/models/ModelSummaryDto.ts
  frontend/src/generated-api/models/PaginationResponseGetProjectsResponseDetailDto.ts
  frontend/src/generated-api/models/ProjectDetailDto.ts
  frontend/src/generated-api/models/RoiRequestDto.ts
  frontend/src/generated-api/models/RoiRequestPayload.ts
  frontend/src/generated-api/models/RoiResponseDto.ts
  frontend/src/generated-api/models/RoiResponsePayload.ts
  frontend/src/generated-api/models/RoiSaveRequestDto.ts
  frontend/src/generated-api/models/SubProjectResponseDto.ts
  frontend/src/generated-api/models/SubProjectSummaryDto.ts
  frontend/src/generated-api/models/TrainingResultRequestDto.ts
  frontend/src/generated-api/models/UpdateProjectRequestDto.ts
  frontend/src/generated-api/models/UploadRoisRequest.ts
  frontend/src/generated-api/models/index.ts
  frontend/src/generated-api/runtime.ts
  frontend/src/utils/canvas-ploygon-utils.ts
  frontend/src/utils/canvas-utils.ts
  frontend/yarn.lock
Labels: ⚙️Chore, 🌈FE

#111 [ BE ] feat/#84 썸네일 및 타일 이미지 생성
  backend/build.gradle
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
  backend/src/main/java/site/pathos/domain/subProject/dto/request/SubProjectTilingRequestDto.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/global/aws/config/AwsClientConfig.java
  backend/src/main/java/site/pathos/global/aws/ec2/Ec2Service.java
  backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
  backend/src/main/java/site/pathos/global/aws/s3/dto/S3UploadFileDto.java
  backend/src/main/java/site/pathos/global/config/AsyncConfig.java
Labels: ✨Feature, 😎BE

#113 [ BE ] feat/#112 ROI 및 이미지 저장 로직 수정
  backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/entity/TissueAnnotation.java
  backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/service/TissueAnnotationService.java
  backend/src/main/java/site/pathos/domain/annotationHistory/service/AnnotationHistoryService.java
  backend/src/main/java/site/pathos/domain/label/entity/Label.java
  backend/src/main/java/site/pathos/domain/label/service/LabelService.java
  backend/src/main/java/site/pathos/domain/modelServer/service/ModelServerService.java
  backend/src/main/java/site/pathos/domain/project/entity/Project.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
  backend/src/main/java/site/pathos/domain/roi/controller/RoiController.java
  backend/src/main/java/site/pathos/domain/roi/dto/request/RoiRequestPayload.java
  backend/src/main/java/site/pathos/domain/roi/dto/response/RoiResponsePayload.java
  backend/src/main/java/site/pathos/domain/roi/entity/Roi.java
  backend/src/main/java/site/pathos/domain/roi/repository/RoiRepository.java
  backend/src/main/java/site/pathos/domain/roi/service/RoiService.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/domain/subProject/service/SubProjectService.java
  backend/src/main/java/site/pathos/global/aws/config/AwsProperty.java
  backend/src/main/java/site/pathos/global/aws/ec2/Ec2Service.java
  backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
  backend/src/main/java/site/pathos/global/callback/CallbackController.java
  backend/src/main/java/site/pathos/global/callback/dto/request/TilingCallbackRequestDto.java
Labels: ✨Feature, 😎BE

#115 [ BE ] feat/#107 프로젝트 상세 조회 기능 추가
  backend/.gitignore
  backend/src/main/java/site/pathos/domain/annotationHistory/entity/AnnotationHistory.java
  backend/src/main/java/site/pathos/domain/annotationHistory/repository/AnnotationHistoryRepository.java
  backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
  backend/src/main/java/site/pathos/domain/project/dto/request/CreateProjectRequestDto.java
  backend/src/main/java/site/pathos/domain/project/dto/request/UpdateProjectRequestDto.java
  backend/src/main/java/site/pathos/domain/project/dto/response/GetProjectDetailResponseDto.java
  backend/src/main/java/site/pathos/domain/project/dto/response/GetProjectsResponseDto.java
  backend/src/main/java/site/pathos/domain/project/dto/response/GetSubProjectResponseDto.java
  backend/src/main/java/site/pathos/domain/project/enums/ModelProcessStatusType.java
  backend/src/main/java/site/pathos/domain/project/enums/ProjectSortType.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/domain/subProject/repository/SubProjectRepository.java
  backend/src/main/java/site/pathos/global/error/BusinessException.java
  backend/src/main/java/site/pathos/global/error/ErrorCode.java
  backend/src/main/java/site/pathos/global/error/ErrorResponse.java
  backend/src/main/java/site/pathos/global/error/GlobalExceptionHandler.java
  backend/src/main/java/site/pathos/global/util/datetime/DateTimeUtils.java
Labels: ✨Feature, 😎BE

#121 [ FE ] feat/#98, #110 shared model / upload / downloaded model 페이지 퍼블리싱
  frontend/package.json
  frontend/public/icons/pathos-text-icon-logo.svg
  frontend/public/images/pathos-logo.png
  frontend/src/app/main/public-space/downloaded-model/page.tsx
  frontend/src/app/main/public-space/shared-model/[id]/page.tsx
  frontend/src/app/main/public-space/shared-model/page.tsx
  frontend/src/app/main/public-space/shared-model/upload/page.tsx
  frontend/src/components/common/delete-modal/index.tsx
  frontend/src/components/common/upload-dropzone/index.tsx
  frontend/src/components/downloaded-model/download-model-edit-modal/index.tsx
  frontend/src/components/public-space/comment-box/comment-item/index.tsx
  frontend/src/components/public-space/comment-box/index.tsx
  frontend/src/components/shared-model/markdown-editor/index.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/src/components/sidebar/sidebar-top-menu/index.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/types/downloaded-model.ts
  frontend/src/types/public-space-comment.ts
  frontend/src/types/shared-model.ts
  frontend/yarn.lock
Labels: ✨Feature, 🎨Design, 🌈FE

#123 [ FE] feat/#92 어노테이션 기능 디벨롭
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/types/annotation.ts
  frontend/src/utils/canvas-drawing-utils.ts
  frontend/src/utils/canvas-ploygon-utils.ts
  frontend/src/utils/canvas-utils.ts
Labels: 🐞Bug, ✨Feature, 🌈FE

#124 [ FE ] feat/#92 셀, 멀티 구현
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/components/annotation/annotation-cell-delete-modal/index.tsx
  frontend/src/components/annotation/annotation-header/index.tsx
  frontend/src/components/annotation/annotation-model-export-modal/index.tsx
  frontend/src/components/annotation/annotation-tool/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/data/dummy.ts
  frontend/src/stores/annotation-shared.ts
  frontend/src/types/annotation.ts
  frontend/src/utils/canvas-ploygon-utils.ts
  frontend/src/utils/canvas-utils.ts
Labels: ✨Feature, 🌈FE

#126 [ FE ] feat/#122 alarm 모달과 settings 페이지 퍼블리싱
  frontend/package.json
  frontend/src/app/main/settings/page.tsx
  frontend/src/components/alarm-modal/index.tsx
  frontend/src/components/settings/name-edit-modal/index.tsx
  frontend/src/components/settings/preferences/index.tsx
  frontend/src/components/sidebar/sidebar-bottom-menu/index.tsx
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/form.tsx
  frontend/yarn.lock
Labels: ✨Feature, 🌈FE

#130 [ BE ] hotfix/#120 project detail 썸네일 이미지 Presigned 적용
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
Labels: 😎BE, 🔥HotFix

#137 [BE] HOTFIX: formdata로 multipart와 json 업로드에 대한 설정 추가
  backend/src/main/java/site/pathos/domain/project/controller/AnnotationController.java
  backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/global/annotation/FormDataRequestBody.java
Labels: ⚙️Chore, 😎BE, 🔥HotFix

#139 [BE] fix: 프로젝트 정렬 기능 버그 수정
  backend/src/main/java/site/pathos/domain/project/repository/ProjectRepository.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
Labels: 🐞Bug, 😎BE

#142 [ BE ] feat/#133 어노테이션 조회 및 프로젝트 생성 수정
  backend/src/main/java/site/pathos/domain/annotationHistory/controller/AnnotationHistoryController.java
  backend/src/main/java/site/pathos/domain/annotationHistory/dto/response/AnnotationHistoryResponseDto.java
  backend/src/main/java/site/pathos/domain/annotationHistory/repository/AnnotationHistoryRepository.java
  backend/src/main/java/site/pathos/domain/annotationHistory/service/AnnotationHistoryService.java
  backend/src/main/java/site/pathos/domain/label/entity/ModelLabel.java
  backend/src/main/java/site/pathos/domain/label/repository/ModelProjectLabelRepository.java
  backend/src/main/java/site/pathos/domain/model/Repository/ModelRepository.java
  backend/src/main/java/site/pathos/domain/model/entity/ProjectModel.java
  backend/src/main/java/site/pathos/domain/modelServer/service/ModelServerService.java
  backend/src/main/java/site/pathos/domain/project/controller/AnnotationController.java
  backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
  backend/src/main/java/site/pathos/domain/project/dto/request/CreateProjectRequestDto.java
  backend/src/main/java/site/pathos/domain/project/dto/response/GetProjectAnnotationResponseDto.java
  backend/src/main/java/site/pathos/domain/project/dto/response/GetSubProjectResponseDto.java
  backend/src/main/java/site/pathos/domain/project/service/AnnotationService.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
  backend/src/main/java/site/pathos/domain/subProject/controller/SubProjectController.java
  backend/src/main/java/site/pathos/domain/subProject/dto/response/SubProjectResponseDto.java
  backend/src/main/java/site/pathos/domain/subProject/repository/SubProjectRepository.java
  backend/src/main/java/site/pathos/domain/subProject/service/SubProjectService.java
Labels: ✨Feature, 😎BE

#141 [ FE ] feat/#125 프로젝트 기능 Api 연결
  frontend/src/app/main/projects/page.tsx
  frontend/src/components/projects/project-create-modal/index.tsx
  frontend/src/generated-api/.openapi-generator/FILES
  frontend/src/generated-api/apis/ProjectAPIApi.ts
  frontend/src/generated-api/apis/ProjectAnnotationAPIApi.ts
  frontend/src/generated-api/apis/index.ts
  frontend/src/generated-api/models/CellDto.ts
  frontend/src/generated-api/models/RoiSaveRequestDto.ts
  frontend/src/generated-api/models/index.ts
Labels: ✨Feature, 🌈FE

#144 [ FE ] feat/#125 프로젝트 생성 시 모델 타입 전달
  frontend/src/app/main/projects/page.tsx
  frontend/src/components/projects/project-create-modal/index.tsx
  frontend/src/generated-api/.openapi-generator/FILES
  frontend/src/generated-api/apis/ProjectAPIApi.ts
  frontend/src/generated-api/apis/ProjectAnnotationAPIApi.ts
  frontend/src/generated-api/apis/index.ts
  frontend/src/generated-api/models/AnnotationHistoryResponseDto.ts
  frontend/src/generated-api/models/CreateProjectRequestDto.ts
  frontend/src/generated-api/models/GetProjectAnnotationResponseDto.ts
  frontend/src/generated-api/models/ModelsDto.ts
  frontend/src/generated-api/models/ProjectModelsDto.ts
  frontend/src/generated-api/models/index.ts
Labels: 🌈FE, 🔥HotFix

#148 [ AA ] feat/#104 docs&help, policies&terms, main 페이지 퍼블리싱
  algorithm/hover_net/augmenters/__init__.py
  algorithm/hover_net/augmenters/__pycache__/__init__.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/arithmetic.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/artistic.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/base.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/blend.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/blur.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/collections.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/color.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/contrast.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/convolutional.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/debug.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/edges.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/flip.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/geometric.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/imgcorruptlike.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/meta.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/overlay.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/pillike.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/pooling.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/segmentation.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/size.cpython-310.pyc
  algorithm/hover_net/augmenters/__pycache__/weather.cpython-310.pyc
  algorithm/hover_net/augmenters/arithmetic.py
  algorithm/hover_net/augmenters/artistic.py
  algorithm/hover_net/augmenters/base.py
  algorithm/hover_net/augmenters/blend.py
  algorithm/hover_net/augmenters/blur.py
  algorithm/hover_net/augmenters/collections.py
  algorithm/hover_net/augmenters/color.py
  algorithm/hover_net/augmenters/contrast.py
  algorithm/hover_net/augmenters/convolutional.py
  algorithm/hover_net/augmenters/debug.py
  algorithm/hover_net/augmenters/edges.py
  algorithm/hover_net/augmenters/flip.py
  algorithm/hover_net/augmenters/geometric.py
  algorithm/hover_net/augmenters/imgcorruptlike.py
  algorithm/hover_net/augmenters/meta.py
  algorithm/hover_net/augmenters/overlay.py
  algorithm/hover_net/augmenters/pillike.py
  algorithm/hover_net/augmenters/pooling.py
  algorithm/hover_net/augmenters/segmentation.py
  algorithm/hover_net/augmenters/size.py
  algorithm/hover_net/augmenters/weather.py
  algorithm/hover_net/models/hovernet/opt.py
  algorithm/hover_net/models/hovernet/run_desc.py
Labels: ✨Feature, 🔨Refactor, 🤖AI, 🧪Experiment

#151 [BE] fix/#147 이미지 슬라이싱 위치를 0,0 으로 수정
  backend/src/main/java/site/pathos/domain/annotation/service/TissueAnnotationService.java
  backend/src/main/java/site/pathos/global/util/image/ImageUtils.java
Labels: 😎BE, 🔥HotFix

#154 [ BE ] feat/#152 어노테이션 api 수정
  backend/src/main/java/site/pathos/domain/annotation/controller/AnnotationController.java
  backend/src/main/java/site/pathos/domain/annotation/dto/request/RoiLabelSaveRequestDto.java
  backend/src/main/java/site/pathos/domain/annotation/dto/response/AnnotationHistoryResponseDto.java
  backend/src/main/java/site/pathos/domain/annotation/dto/response/GetProjectAnnotationResponseDto.java
  backend/src/main/java/site/pathos/domain/annotation/dto/response/RoiResponsePayload.java
  backend/src/main/java/site/pathos/domain/annotation/repository/AnnotationHistoryRepository.java
  backend/src/main/java/site/pathos/domain/annotation/repository/ProjectLabelRepository.java
  backend/src/main/java/site/pathos/domain/annotation/service/AnnotationService.java
  backend/src/main/java/site/pathos/domain/model/dto/TrainingResultRequestDto.java
  backend/src/main/java/site/pathos/domain/model/repository/ProjectModelRepository.java
  backend/src/main/java/site/pathos/domain/model/service/ModelServerService.java
  backend/src/main/java/site/pathos/domain/project/dto/response/SubProjectSummaryDto.java
  backend/src/main/java/site/pathos/domain/project/entity/ProjectLabel.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
Labels: ✨Feature, 😎BE

#156 [ FE ] release: 프론트엔드 작업을 업로드 05.16
  frontend/src/app/main/projects/page.tsx
  frontend/src/components/projects/project-create-modal/index.tsx
  frontend/src/generated-api/.openapi-generator/FILES
  frontend/src/generated-api/apis/ProjectAPIApi.ts
  frontend/src/generated-api/apis/ProjectAnnotationAPIApi.ts
  frontend/src/generated-api/apis/index.ts
  frontend/src/generated-api/models/AnnotationHistoryResponseDto.ts
  frontend/src/generated-api/models/CellDto.ts
  frontend/src/generated-api/models/CreateProjectRequestDto.ts
  frontend/src/generated-api/models/GetProjectAnnotationResponseDto.ts
  frontend/src/generated-api/models/ModelsDto.ts
  frontend/src/generated-api/models/ProjectModelsDto.ts
  frontend/src/generated-api/models/RoiSaveRequestDto.ts
  frontend/src/generated-api/models/index.ts
Labels: ⚙️Chore, 🌈FE

#157 [ AA ] docs: 논문세미나, 데이터타입 프로토타입 및 실험 발표 자료 업로드
  algorithm/docs/HITL_evaluation_meeting.pdf
  algorithm/docs/OCELOT_paper_review.pdf
  algorithm/docs/PathOs_datatype_pipeline.pdf
  algorithm/docs/README.md
Labels: 📄Docs, 🤖AI

#158 [ BE ] feat: tissue 업로드 및 삭제 로직 수정
  backend/src/main/java/site/pathos/domain/annotation/controller/AnnotationController.java
  backend/src/main/java/site/pathos/domain/annotation/entity/Roi.java
  backend/src/main/java/site/pathos/domain/annotation/service/AnnotationService.java
  backend/src/main/java/site/pathos/domain/annotation/service/TissueAnnotationService.java
Labels: 🐞Bug, 😎BE

#159 [ BE ] feat/#140 마이페이지 및 알림 기능 구현
  backend/build.gradle
  backend/src/main/java/site/pathos/PathosApplication.java
  backend/src/main/java/site/pathos/domain/annotation/repository/ModelProjectLabelRepository.java
  backend/src/main/java/site/pathos/domain/model/dto/TrainingResultRequestDto.java
  backend/src/main/java/site/pathos/domain/model/event/ProjectRunCompletedEvent.java
  backend/src/main/java/site/pathos/domain/model/event/ProjectTrainCompletedEvent.java
  backend/src/main/java/site/pathos/domain/model/service/ModelServerService.java
  backend/src/main/java/site/pathos/domain/notification/controller/NotificationController.java
  backend/src/main/java/site/pathos/domain/notification/dto/response/GetNotificationsResponseDto.java
  backend/src/main/java/site/pathos/domain/notification/entity/NotificationType.java
  backend/src/main/java/site/pathos/domain/notification/entity/UserNotification.java
  backend/src/main/java/site/pathos/domain/notification/entity/UserNotificationSetting.java
  backend/src/main/java/site/pathos/domain/notification/enums/NotificationTypeCode.java
  backend/src/main/java/site/pathos/domain/notification/listener/NotificationEventListener.java
  backend/src/main/java/site/pathos/domain/notification/repository/NotificationTypeRepository.java
  backend/src/main/java/site/pathos/domain/notification/repository/UserNotificationRepository.java
  backend/src/main/java/site/pathos/domain/notification/repository/UserNotificationSettingRepository.java
  backend/src/main/java/site/pathos/domain/notification/service/UserNotificationService.java
  backend/src/main/java/site/pathos/domain/notification/service/UserNotificationSettingService.java
  backend/src/main/java/site/pathos/domain/project/event/ProjectSvsUploadCompletedEvent.java
  backend/src/main/java/site/pathos/domain/project/service/SubProjectService.java
  backend/src/main/java/site/pathos/domain/sharedProject/event/SharedProjectCommentReceivedEvent.java
  backend/src/main/java/site/pathos/domain/user/controller/UserController.java
  backend/src/main/java/site/pathos/domain/user/dto/GetUserSettingsResponseDto.java
  backend/src/main/java/site/pathos/domain/user/dto/UpdateNotificationSettingsRequestDto.java
  backend/src/main/java/site/pathos/domain/user/dto/UpdateUserNameRequestDto.java
  backend/src/main/java/site/pathos/domain/user/entity/User.java
  backend/src/main/java/site/pathos/domain/user/service/UserService.java
  backend/src/main/java/site/pathos/global/common/PaginationResponse.java
  backend/src/main/java/site/pathos/global/entity/BaseTimeEntity.java
  backend/src/main/java/site/pathos/global/error/ErrorCode.java
  backend/src/main/java/site/pathos/global/util/datetime/DateTimeUtils.java
Labels: ✨Feature, 😎BE

#160 [BE] fix: ModelProjectLabelRepository 수정 오류 롤백
  backend/src/main/java/site/pathos/domain/annotation/repository/ModelProjectLabelRepository.java
Labels: 🐞Bug, 😎BE

#162 [ BE ] fix/#158 roi 및 label 저장로직 수정
  backend/src/main/java/site/pathos/domain/annotation/dto/request/RoiLabelSaveRequestDto.java
  backend/src/main/java/site/pathos/domain/annotation/entity/Roi.java
  backend/src/main/java/site/pathos/domain/annotation/service/AnnotationService.java
  backend/src/main/java/site/pathos/domain/annotation/service/TissueAnnotationService.java
  backend/src/main/java/site/pathos/domain/sharedProject/entity/DataSet.java
Labels: 🔨Refactor, 😎BE

#171 퍼블릭 스페이스 수정
  backend/src/main/java/site/pathos/domain/model/entity/Model.java
  backend/src/main/java/site/pathos/domain/model/entity/UserModel.java
  backend/src/main/java/site/pathos/domain/model/repository/UserModelRepository.java
  backend/src/main/java/site/pathos/domain/sharedProject/controller/PublicSpaceController.java
  backend/src/main/java/site/pathos/domain/sharedProject/dto/request/CreateCommentRequestDto.java
  backend/src/main/java/site/pathos/domain/sharedProject/dto/request/UpdateCommentRequestDto.java
  backend/src/main/java/site/pathos/domain/sharedProject/dto/response/GetSharedProjectCommentsResponseDto.java
  backend/src/main/java/site/pathos/domain/sharedProject/entity/Comment.java
  backend/src/main/java/site/pathos/domain/sharedProject/entity/DownloadLog.java
  backend/src/main/java/site/pathos/domain/sharedProject/entity/SharedProject.java
  backend/src/main/java/site/pathos/domain/sharedProject/enums/CommentTag.java
  backend/src/main/java/site/pathos/domain/sharedProject/repository/CommentRepository.java
  backend/src/main/java/site/pathos/domain/sharedProject/repository/DownloadLogRepository.java
  backend/src/main/java/site/pathos/domain/sharedProject/repository/SharedProjectRepository.java
  backend/src/main/java/site/pathos/domain/sharedProject/service/PublicSpaceService.java
  backend/src/main/java/site/pathos/global/error/ErrorCode.java
Labels: ✨Feature, 😎BE, 🔥HotFix

#187 [BE] refactor: 공유 프로젝트 상세 조회에 프로젝트 ID 추가
  backend/src/main/java/site/pathos/domain/sharedProject/dto/response/GetSharedProjectDetailResponseDto.java
  backend/src/main/java/site/pathos/domain/sharedProject/entity/SharedProject.java
  backend/src/main/java/site/pathos/domain/sharedProject/service/PublicSpaceService.java
Labels: 🔨Refactor, 😎BE

#191 [ FE ] feat/#183 어노테이션 저장, 트레인 함수 롤백
  frontend/src/components/annotation/annotation-header/index.tsx
Labels: 🌈FE, 🔥HotFix

#192 [ FE ] feat/#183 자잘한 에러 Hotfix
  frontend/src/app/oauth/callback/page.tsx
  frontend/src/components/annotation/annotation-header/index.tsx
  frontend/src/components/annotation/annotation-sidebar/index.tsx
  frontend/src/components/sidebar/sidebar-profile/index.tsx
  frontend/src/generated-api/apis/ProfileAPIApi.ts
  frontend/src/generated-api/models/GetProjectAnnotationResponseDto.ts
  frontend/src/generated-api/models/ModelsDto.ts
  frontend/src/utils/model-type-label.ts
Labels: 🌈FE, 🔥HotFix

#194 [FE] fix: build error fix
  frontend/src/generated-api/apis/PublicSpaceAPIApi.ts
Labels: 🌏Deploy, 🌈FE, 🔥HotFix

#195 [FE] fix: 이미지 최적화 Off
  frontend/src/components/annotation/annotation-subproject-slider/index.tsx
  frontend/src/components/projects/subproject-table/index.tsx
Labels: 🌈FE, 🔥HotFix

#196 [FE] fix: 자동 다운로드 기능 제거
  frontend/src/components/annotation/annotation-header/index.tsx
Labels: 🌈FE
