Repository kookmin-sw/capstone-2025-08, pull requests merged in 2025-03, with the labels that each got.

#2 [ FE ] init/#1 next.js 프로젝트 초기 세팅
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: ⚙️Chore, 🌈FE

#7 [FE] feat/#6 Openseadragon Viewer 설정
  frontend/package.json
  frontend/src/components/ui/button.tsx
  frontend/src/hooks/useOSDViewer.ts
  frontend/src/lib/utils.ts
  frontend/src/types/geotiff-tilesource.d.ts
  frontend/src/types/openseadragon.d.ts
  frontend/yarn.lock
Labels: ✨Feature, 🌈FE

#10 [ BE ] init: springboot 초기 세팅
  backend/.gitignore
  backend/build.gradle
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/site/pathos/PathosApplication.java
  backend/src/test/java/site/pathos/PathosApplicationTests.java
Labels: ⚙️Chore, 😎BE
