Repository kookmin-sw/capstone-2025-08, pull requests merged in 2025-04, with the labels that each got.

#15 [ BE ] chore/#14 모델 서버 초기 세팅
  ai/.dockerignore
  ai/.gitignore
  ai/app.py
  ai/main.py
Labels: ⚙️Chore, 😎BE

#17 [ BE ] feat/#16 모델 서버 SQS 연동
  ai/config.py
  ai/core/__init__.py
  ai/core/sqs.py
  ai/main.py
Labels: ✨Feature, 😎BE

#18 [ BE ] chore/#13 스프링 서버 배포 및 CI/CD 파이프라인 구축
  backend/.github/workflows/ci-cd.yml
  backend/Dockerfile
Labels: ⚙️Chore, 🌏Deploy, 😎BE

#20 [ BE ] feat/#19 Entity 클래스 생성
  backend/src/main/java/site/pathos/domain/annotation/cellAnnotation/entity/TissueAnnotation.java
  backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/entity/CellAnnotation.java
  backend/src/main/java/site/pathos/domain/annotationHistory/entity/AnnotationHistory.java
  backend/src/main/java/site/pathos/domain/comment/entity/Comment.java
  backend/src/main/java/site/pathos/domain/dataSet/entity/DataSet.java
  backend/src/main/java/site/pathos/domain/dataSet/entity/DataType.java
  backend/src/main/java/site/pathos/domain/inferenceHistory/entity/InferenceHistory.java
  backend/src/main/java/site/pathos/domain/model/entitiy/Model.java
  backend/src/main/java/site/pathos/domain/project/entity/Project.java
  backend/src/main/java/site/pathos/domain/roi/entity/Roi.java
  backend/src/main/java/site/pathos/domain/sharedProject/entity/SharedProject.java
  backend/src/main/java/site/pathos/domain/subProject/SubProject.java
  backend/src/main/java/site/pathos/domain/user/entity/User.java
  backend/src/main/java/site/pathos/domain/userModel/entity/UserModel.java
Labels: ✨Feature, 😎BE

#21 [ FE ] feat/#8 Annotation 컴포넌트 코드 이동 및 리팩토링
  frontend/package.json
  frontend/src/app/main/projects/annotation/[id]/layout.tsx
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/app/main/projects/page.tsx
  frontend/src/components/annotation/annotation-header.tsx
  frontend/src/components/annotation/annotation-tool.tsx
  frontend/src/components/annotation/annotation-viewer.tsx
  frontend/src/components/annotation/control-panel.tsx
  frontend/src/data/dummy.ts
  frontend/src/hooks/use-osdviewer.ts
  frontend/src/types/project-schema.ts
  frontend/src/utils/canvas-utils.ts
  frontend/yarn.lock
Labels: ✨Feature, 🌈FE

#24 [ AA ] init/#23 DeepLabV3+ 레포지토리 clone
  algorithm/DeepLabV3Plus-Pytorch/LICENSE
  algorithm/DeepLabV3Plus-Pytorch/README.md
  algorithm/DeepLabV3Plus-Pytorch/datasets/__init__.py
  algorithm/DeepLabV3Plus-Pytorch/datasets/cityscapes.py
  algorithm/DeepLabV3Plus-Pytorch/datasets/data/train_aug.txt
  algorithm/DeepLabV3Plus-Pytorch/datasets/utils.py
  algorithm/DeepLabV3Plus-Pytorch/datasets/voc.py
  algorithm/DeepLabV3Plus-Pytorch/main.py
  algorithm/DeepLabV3Plus-Pytorch/metrics/__init__.py
  algorithm/DeepLabV3Plus-Pytorch/metrics/stream_metrics.py
  algorithm/DeepLabV3Plus-Pytorch/network/__init__.py
  algorithm/DeepLabV3Plus-Pytorch/network/_deeplab.py
  algorithm/DeepLabV3Plus-Pytorch/network/backbone/__init__.py
  algorithm/DeepLabV3Plus-Pytorch/network/backbone/hrnetv2.py
  algorithm/DeepLabV3Plus-Pytorch/network/backbone/mobilenetv2.py
  algorithm/DeepLabV3Plus-Pytorch/network/backbone/resnet.py
  algorithm/DeepLabV3Plus-Pytorch/network/backbone/xception.py
  algorithm/DeepLabV3Plus-Pytorch/network/modeling.py
  algorithm/DeepLabV3Plus-Pytorch/network/utils.py
  algorithm/DeepLabV3Plus-Pytorch/predict.py
  algorithm/DeepLabV3Plus-Pytorch/requirements.txt
  algorithm/DeepLabV3Plus-Pytorch/samples/114_image.png
  algorithm/DeepLabV3Plus-Pytorch/samples/114_overlay.png
  algorithm/DeepLabV3Plus-Pytorch/samples/114_pred.png
  algorithm/DeepLabV3Plus-Pytorch/samples/114_target.png
  algorithm/DeepLabV3Plus-Pytorch/samples/1_image.png
  algorithm/DeepLabV3Plus-Pytorch/samples/1_overlay.png
  algorithm/DeepLabV3Plus-Pytorch/samples/1_pred.png
  algorithm/DeepLabV3Plus-Pytorch/samples/1_target.png
  algorithm/DeepLabV3Plus-Pytorch/samples/23_image.png
  algorithm/DeepLabV3Plus-Pytorch/samples/23_overlay.png
  algorithm/DeepLabV3Plus-Pytorch/samples/23_pred.png
  algorithm/DeepLabV3Plus-Pytorch/samples/23_target.png
  algorithm/DeepLabV3Plus-Pytorch/samples/city_1_overlay.png
  algorithm/DeepLabV3Plus-Pytorch/samples/city_1_target.png
  algorithm/DeepLabV3Plus-Pytorch/samples/city_6_overlay.png
  algorithm/DeepLabV3Plus-Pytorch/samples/city_6_target.png
  algorithm/DeepLabV3Plus-Pytorch/samples/visdom-screenshoot.png
  algorithm/DeepLabV3Plus-Pytorch/utils/__init__.py
  algorithm/DeepLabV3Plus-Pytorch/utils/ext_transforms.py
  algorithm/DeepLabV3Plus-Pytorch/utils/loss.py
  algorithm/DeepLabV3Plus-Pytorch/utils/scheduler.py
  algorithm/DeepLabV3Plus-Pytorch/utils/utils.py
  algorithm/DeepLabV3Plus-Pytorch/utils/visualizer.py
  algorithm/README.md
Labels: ⚙️Chore, 🤖AI

#28 [ FE ] feat/#8 디렉토리, 파일명 리팩토링
  frontend/src/app/main/layout.tsx
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/components/annotation/annotation-control-panel/index.tsx
  frontend/src/components/annotation/annotation-header/index.tsx
  frontend/src/components/annotation/annotation-tool/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/src/components/sidebar/sidebar-bottom-menu/index.tsx
  frontend/src/components/sidebar/sidebar-profile/index.tsx
  frontend/src/components/sidebar/sidebar-top-menu/index.tsx
Labels: 🔨Refactor, 🌈FE

#36 [ FE ] feat/#22 Drawing 기능 펜슬 관련 에러 HOTFIX
  frontend/src/app/main/layout.tsx
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/components/annotation/annotation-tool/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/data/dummy.ts
  frontend/src/utils/canvas-utils.ts
  frontend/yarn.lock
Labels: 🐞Bug, 🌈FE

#35 [ AA ] feat/#34 Deeplabv3+_HITL experiment & evaluation
  algorithm/Deeplabv3+_HITL/DLv3p_HITL_lab_meeting.pdf
  algorithm/Deeplabv3+_HITL/DeeplabV3+_seg_test0.ipynb
  algorithm/Deeplabv3+_HITL/README.md
Labels: 🤖AI, 🧪Experiment

#37 [ FE ] fix/#27 roi 에러 해결
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/utils/canvas-utils.ts
Labels: 🐞Bug, 🌈FE

#42 [ BE ] feat/#32 s3 관련 설정 및 로직 구현
  backend/build.gradle
  backend/src/main/java/site/pathos/PathosApplication.java
  backend/src/main/java/site/pathos/global/aws/s3/AmazonS3Configuration.java
  backend/src/main/java/site/pathos/global/aws/s3/AwsProperty.java
  backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
Labels: ⚙️Chore, ✨Feature, 😎BE

#45 [ BE ] fix/#44 빌드 관련 오류 수정
  backend/build.gradle
  backend/src/main/java/site/pathos/domain/project/entity/Project.java
Labels: 🐞Bug, 😎BE

#50 [ FE ] feat/#39 (모델 인퍼런스 후) png 파일 오버레이 시 드로잉, 지우기 기능 구현
  frontend/public/0_0.png
  frontend/public/0_1.png
  frontend/public/0_2.png
  frontend/public/1_0.png
  frontend/public/1_1.png
  frontend/public/1_2.png
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/data/dummy.ts
  frontend/src/types/annotation.ts
  frontend/src/utils/canvas-drawing-utils.ts
  frontend/src/utils/canvas-image-utils.ts
  frontend/src/utils/canvas-roi-utils.ts
  frontend/src/utils/canvas-utils.ts
Labels: ✨Feature, 🌈FE

#49 [ BE ] feat/#33 데이터 전처리 및 학습/추론 결과물 처리
  ai/core/image_processor.py
  ai/core/sqs.py
  ai/main.py
Labels: ✨Feature, 😎BE

#58 [ BE ] chore/#57 접근 디렉토리 절대 위치로 변경
  .github/workflows/ci-cd.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
Labels: 😎BE

#54 [ FE ] feat/#43 어노테이션 페이지 퍼블리싱
  frontend/package.json
  frontend/src/app/main/layout.tsx
  frontend/src/app/main/projects/annotation/[id]/layout.tsx
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/components/annotation/annotation-header/index.tsx
  frontend/src/components/annotation/annotation-sidebar/index.tsx
  frontend/src/components/annotation/annotation-subproject-slider/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/data/dummy.ts
  frontend/src/lib/utils.ts
  frontend/src/types/project-schema.ts
  frontend/yarn.lock
Labels: ✨Feature, 🔨Refactor, 🌈FE

#63 Backend/chore/#62 swagger setting
  backend/build.gradle
  backend/src/main/java/site/pathos/domain/annotation/cellAnnotation/repository/CellAnnotationRepository.java
  backend/src/main/java/site/pathos/domain/annotationHistory/service/AnnotationHistoryService.java
  backend/src/main/java/site/pathos/domain/roi/controller/RoiController.java
  backend/src/main/java/site/pathos/global/config/SwaggerConfig.java
Labels: ⚙️Chore, 😎BE

#64 [ BE ] Backend/app develop Release 04.21
  backend/build.gradle
  backend/src/main/java/site/pathos/domain/annotation/cellAnnotation/repository/CellAnnotationRepository.java
  backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/entity/AnnotationType.java
  backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/service/TissueAnnotationService.java
  backend/src/main/java/site/pathos/domain/annotationHistory/controller/AnnotationHistoryController.java
  backend/src/main/java/site/pathos/domain/annotationHistory/dto/response/AnnotationHistoryResponseDto.java
  backend/src/main/java/site/pathos/domain/annotationHistory/entity/AnnotationHistory.java
  backend/src/main/java/site/pathos/domain/annotationHistory/service/AnnotationHistoryService.java
  backend/src/main/java/site/pathos/domain/model/Repository/ModelRepository.java
  backend/src/main/java/site/pathos/domain/model/entity/Model.java
  backend/src/main/java/site/pathos/domain/model/service/ModelService.java
  backend/src/main/java/site/pathos/domain/modelServer/dto/request/TrainingRequestDto.java
  backend/src/main/java/site/pathos/domain/modelServer/dto/request/TrainingResultRequestDto.java
  backend/src/main/java/site/pathos/domain/modelServer/service/ModelServerService.java
  backend/src/main/java/site/pathos/domain/roi/controller/RoiController.java
  backend/src/main/java/site/pathos/domain/roi/dto/request/RoiPayload.java
  backend/src/main/java/site/pathos/domain/roi/repository/RoiRepository.java
  backend/src/main/java/site/pathos/domain/roi/service/RoiService.java
  backend/src/main/java/site/pathos/domain/userModel/entity/UserModel.java
  backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
  backend/src/main/java/site/pathos/global/config/SwaggerConfig.java
  backend/src/main/java/site/pathos/global/util/image/ImageTile.java
  backend/src/main/java/site/pathos/global/util/image/ImageUtils.java
Labels: 🌏Deploy, 😎BE

#66 [BE] chore/#65 cors 임시 설정
  .github/workflows/ci-cd.yml
  backend/src/main/java/site/pathos/global/config/WebConfig.java
Labels: ⚙️Chore, 😎BE

#67 [ FE ] feat/#43 어노테이션 페이지 상태관리 구조 리팩토링
  frontend/public/subproject-thumbnail.png
  frontend/src/app/main/projects/annotation/[id]/page.tsx
  frontend/src/components/annotation/annotation-subproject-slider/index.tsx
  frontend/src/components/annotation/annotation-viewer/index.tsx
  frontend/src/data/dummy.ts
Labels: 🐞Bug, 🔨Refactor, 🌈FE

#73 [ BE ] feat/#72 subproject detail 불러오는 api 구현
  backend/src/main/java/site/pathos/domain/annotationHistory/dto/response/AnnotationHistorySummaryDto.java
  backend/src/main/java/site/pathos/domain/annotationHistory/entity/AnnotationHistory.java
  backend/src/main/java/site/pathos/domain/annotationHistory/repository/AnnotationHistoryRepository.java
  backend/src/main/java/site/pathos/domain/model/ModelSummaryDto.java
  backend/src/main/java/site/pathos/domain/model/entity/Model.java
  backend/src/main/java/site/pathos/domain/model/entity/ModelType.java
  backend/src/main/java/site/pathos/domain/model/service/ModelService.java
  backend/src/main/java/site/pathos/domain/modelServer/service/ModelServerService.java
  backend/src/main/java/site/pathos/domain/project/entity/Project.java
  backend/src/main/java/site/pathos/domain/roi/service/RoiService.java
  backend/src/main/java/site/pathos/domain/subProject/controller/SubProjectController.java
  backend/src/main/java/site/pathos/domain/subProject/dto/response/SubProjectResponseDto.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/domain/subProject/repository/SubProjectRepository.java
  backend/src/main/java/site/pathos/domain/subProject/service/SubProjectService.java
  backend/src/main/java/site/pathos/domain/userModel/repository/UserModelRepository.java
Labels: ✨Feature, 😎BE

#76 [ BE ] feat/#74 project info 불러오는 로직 추가
  .github/workflows/ci-cd.yml
  backend/src/main/java/site/pathos/domain/annotationHistory/controller/AnnotationHistoryController.java
  backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
  backend/src/main/java/site/pathos/domain/project/dto/response/ProjectDetailDto.java
  backend/src/main/java/site/pathos/domain/project/repository/ProjectRepository.java
  backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
  backend/src/main/java/site/pathos/domain/subProject/controller/SubProjectController.java
  backend/src/main/java/site/pathos/domain/subProject/dto/response/SubProjectResponseDto.java
  backend/src/main/java/site/pathos/domain/subProject/dto/response/SubProjectSummaryDto.java
  backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
  backend/src/main/java/site/pathos/domain/subProject/repository/SubProjectRepository.java
  backend/src/main/java/site/pathos/domain/subProject/service/SubProjectService.java
Labels: ✨Feature, 😎BE
